version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-major"]
    versioning-strategy: increase-if-necessary
