name: "🐞 Bug report"
description: Сообщить об ошибке
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes: { label: Что произошло?, description: Опиши баг, шаги воспроизведения }
    validations: { required: true }
  - type: input
    id: env
    attributes: { label: Окружение, placeholder: "OS, Node, браузер" }
