name: Gitleaks Secret Scan

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    # не гоняем на PR от dependabot
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'dependabot' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan with Gitleaks
        id: scan
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Никаких args — экшен сам подберёт дефолтные правила

      # Загружаем отчёт, но не валим пайплайн, даже если файла нет
      - name: Upload SARIF to Security tab (if present)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
        continue-on-error: true

      # Держим job зелёной даже при находках — алерты будут в Security → Code scanning
      - name: Keep CI green
        if: failure()
        run: echo "Gitleaks found issues. See Security tab (SARIF uploaded)."