name: Gitleaks Secret Scan

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    # Полностью пропускаем job для Dependabot, чтобы не было красных ранoв
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gitleaks scan (SARIF)
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --redact --report-format sarif --report-path gitleaks-results.sarif
        # на всякий случай не фейлим пайплайн, даже если что-то упрётся в окружение
        continue-on-error: true

      - name: Upload SARIF to Security tab
        if: ${{ hashFiles('gitleaks-results.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-results.sarif
