name: Gitleaks

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install gitleaks (binary)
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_$(uname -m).tar.gz \
          | tar -xz gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks
          gitleaks version

      # не валим сборку: всегда возвращаем 0, но формируем SARIF
      - name: Scan
        run: |
          gitleaks detect --no-git --source . \
            --report-format sarif --report-path gitleaks-results.sarif || true

      - name: Upload SARIF to Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-results.sarif
