name: Gitleaks Secret Scan

on:
  workflow_dispatch:
  push:
    branches: [main] # на пуш в main
  pull_request:
    branches: [main, dev] # и на PR в main/dev

permissions:
  contents: read
  security-events: write # нужно для загрузки SARIF в Security tab

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Официальный экшен. Генерируем SARIF и не "роняем" сборку.
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: >
            --no-banner
            --redact
            --report-format sarif
            --report-path gitleaks-results.sarif
            --exit-code 0 # <- всегда 0, чтобы job был зелёным

      # Загружаем SARIF только если файл существует (иначе не падаем).
      - name: Upload SARIF to Security tab
        if: always() && hashFiles('gitleaks-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-results.sarif
