name: Gitleaks Secret Scan

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Scan with Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --no-git --redact --report-format sarif --report-path gitleaks-results.sarif

      - name: Upload SARIF to Security tab (if present)
        if: hashFiles('gitleaks-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-results.sarif
